service: hits-data-collection-api

provider:
  name: aws
  runtime: nodejs12.x
  profile: ${env:AWS_PROFILE}
  region: ${env:REGION}
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:ap-southeast-2:972124391741:table/hitsEventData
        - arn:aws:dynamodb:ap-southeast-2:972124391741:table/hitsGames


functions:
  writeHitsEvent:
    handler: src/postHitsEventHandler.postHitsEventHandler
    events:
      - http:
          path: "/hits-event"
          method: post
          cors: true

  initialiseHitsGame:
    handler: src/initialiseHitsGame.initialiseHitsGame
    events:
      - http:
          path: "/hits-initialise"
          method: post
          cors: true

